---
abstract: 'Generate perl tags for vim'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Vim-Tag
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Accessor::Constructor: 0
  File::Find::Upwards: 0
  File::Slurp: 0
  Getopt::Inherited: 0
  Hash::Rename: 0
  UNIVERSAL::require: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Vim-Tag
  homepage: http://search.cpan.org/dist/Vim-Tag/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/vim-tag.git
version: 0.04
